# Generated by Django 3.0.6 on 2020-05-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classcrud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classblog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
